[tool.poetry]
name = "istari_mcp_server"
version = "1.0.0"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
mcp = "=1.9.4"
dotenv = "=0.9.9"
pillow = "*"
istari_digital_client = "=7.15.1"
