import asyncio
import multiprocessing
import os
import random
import tempfile

from time import sleep
from typing import Callable

from istari_digital_client import Client, Configuration, Job, Model, NewSource
from istari_digital_client.models import JobStatusName

from shared.constants import REG_URL, REG_AUTH_TOKEN
from evaluators.regex_evaluator import evaluate_query
from evaluators.query_status import QueryStatus


job_list = []

def get_client():
  configuration = Configuration(
      registry_url=REG_URL,
      registry_auth_token=REG_AUTH_TOKEN)

  return Client(config = configuration)


def submit_job(model_id: str,
               function: str,
               tool_name: str,
               tool_ver: str = None,
               operating_system = None,
               params_file: str = None,
               assigned_agent_id: str = None,
               sources: list[NewSource | str] = None) -> Job:
  client = get_client()
  job =  client.add_job(model_id,
                        function = function,
                        tool_name = tool_name,
                        tool_version = tool_ver,
                        operating_system = operating_system,
                        parameters_file = params_file,
                        assigned_agent_id = assigned_agent_id,
                        sources = sources)
  job_list.append(job.id)
  return job


def wait_for_job(job) -> Job:
  client = get_client()
  empty_str = ' ' * 64
  while not job.status.name in [JobStatusName.COMPLETED, 
                                JobStatusName.FAILED,
                                JobStatusName.CANCELED]:
    sleep(1)
    job = client.get_job(job.id)
    print(empty_str, end="\r")
    job_stat = format_str(job.status.name, 1)
    print(f"Job Status: {job_stat}", end="\r")

  if job.id in job_list:
    job_list.remove(job.id)

  print(empty_str, end="\r")
  return job


def wait_for_all_jobs():
  client = get_client()
  for job_id in job_list:
    job = client.get_job(job_id)
    wait_for_job(job)


def get_model_display_name(model_id: str) -> str:
  client = get_client()
  mod = client.get_model(model_id)
  disp_name = mod.display_name
  if disp_name is None:
    disp_name,_ = os.path.splitext(mod.name)

  return disp_name

def get_latest_revision(model_id: str) -> str:
  client = get_client()
  mod = client.get_model(model_id)
  mod_revs = mod.file.revisions
  ret_rev = None
  for mod_rev in mod_revs:
    if ret_rev == None or ret_rev.created < mod_rev.created:
      ret_rev = mod_rev

  return ret_rev.id
  

def wait_for_new_version(model_id: str) -> Model:
  client = get_client()
  empty_str = ' ' * 64
  mod = client.get_model(model_id)
  revs = mod.file.revisions
  mod_name = revs[0].display_name
  latest_rev = revs[-1]
  rev_count = len(revs)
  while True:
    print(empty_str, end="\r")
    print(f"Polling for model updates: {mod_name}",
          end="\r")
    sleep(5)
    mod = client.get_model(model_id)
    revs = mod.file.revisions
    new_rev_count = len(revs)
    if new_rev_count != rev_count:
      latest_rev = revs[-1]
      break

  print(empty_str, end="\r")
  print(f"Model update detected: {mod_name}")
  return latest_rev


def download_artifact_orig(model_id: str,
                      artifact_name: str,
                      dest_file: str = None):
  client = get_client()
  art = None
  pg_idx = 1
  while True:
    art_list = client.list_model_artifacts(model_id,
                                           page = pg_idx)
    art_items = art_list.items
    if len(art_items) == 0:
      break
    
    for itm in art_items:
      if itm.name == artifact_name:
        art = itm
        break

    if art is not None: break
    pg_idx += 1

  if art is None:
    raise FileNotFoundError(f"Artifact not found: {artifact_name}")
  else:
    if dest_file is None:
      dest_file = artifact_name
    with open(dest_file, 'wb') as fout:
      fout.write(art.read_bytes())


def download_artifact_data(model_id: str,
                           artifact_name: str) -> bytes:
  client = get_client()
  mod = client.get_model(model_id)
  mod_rev_id = mod.file.revisions[-1].id

  pg_idx = 1
  while True:
    art_list = client.list_model_artifacts(model_id,
                                           page = pg_idx)
    arts = art_list.items
    if len(arts) == 0:
      break
    
    # Find artifact with name matching artifact_name and generated by the latest
    # version of the model
    for art in arts:
      if art.name == artifact_name:
        for art_rev in art.revisions:
          for art_rev_src in art_rev.sources:
            try:
              if art_rev_src.revision_id == mod_rev_id:
                return get_artifact_data(art_rev)
            except Exception as excp:
              print(f"Exception: {excp}")

    pg_idx += 1

  raise FileNotFoundError(f"Artifact not found: {artifact_name}")


def download_artifact(model_id: str,
                      artifact_name: str,
                      dest_file: str = None) -> None:
  """
  Downloads the artifact associated with the latest version of the model.

  Throws FileNotFoundError if the artifact is not found.
  """
  art_bytes = download_artifact_data(model_id,
                                     artifact_name)
  if dest_file is None:
    dest_file = artifact_name
  with open(dest_file, 'wb') as fout:
    fout.write(art_bytes)


def get_artifact_data(art_rev: object) -> bytes:
  """
  Searches the model cache for the specified artifact revision. If there is a 
  cache hit, returns the cached data. Otherwise, the artifact is downloaded 
  from the Istari platform and cached.
  """
  model_cache_dir = tempfile.gettempdir()
  art_file = os.path.join(model_cache_dir,
                          art_rev.id)
  art_bytes = None
  if False: #os.path.exists(art_file):
    with open(art_file, 'rb') as fin:
      art_bytes = fin.read()
  else:
    art_bytes = art_rev.read_bytes()
    with open(art_file, 'wb') as fout:
      fout.write(art_bytes)
    
  return art_bytes


async def submit_query(query: str,
                 item_objs: list[str],
                 eval_item: Callable[[str, str], QueryStatus],
                 max_wait_time: int) -> QueryStatus:
  rand_wait = max_wait_time / random.randint(1, 50)
  sleep(rand_wait)
  results = []
  for item_obj in item_objs:
    result = await eval_item(query,
                       item_obj)
    results.append(result)

  return (item_objs, results)


async def search_artifact_data(query: list[str],
                               art_iter: iter,
                               eval_item: Callable[[str, str], QueryStatus] = evaluate_query,
                               batch_group_count: int = 10,
                               max_iter_delay: int = 2,
                               add_items: bool = False) -> list[str]:
  batch_group = []
  args = []
  query_results = []
  iter_idx = 0
  batch_idx = 1
  is_last = False
  print('Starting processing')
  while True:
    try:
      art_item = art_iter.__next__()
      batch_group.append(art_item)
      iter_idx += 1
    except StopIteration:
      is_last = True

    if not iter_idx % batch_group_count or is_last:
      print(f"Searching batch: {batch_idx}")
      batch_idx += 1
      #args.append((query, batch_group, eval_item, max_iter_delay))
      query_result = await submit_query(query, batch_group, eval_item, max_iter_delay)
      query_results.append(query_result)

      if is_last: break
      batch_group = []

  #print('Starting multiprocessing')
  #with multiprocessing.Pool(processes=12) as pool:
  #  query_results = pool.starmap(submit_query, args)
  print('Finished')

  matches = []
  prev_art_item = None
  prev_match = False
  added_prev_item = False
  for iter_items, batch_results in query_results:
    for iter_item, query_result in zip(iter_items, batch_results):
      if query_result == QueryStatus.MATCH:
        print('Found match')
        if add_items and prev_art_item and not added_prev_item: 
          matches.append(prev_art_item)

        matches.append(iter_item)
        prev_art_item = iter_item
        added_prev_item = True
        prev_match = True
      elif prev_match:
        matches.append(iter_item)
        prev_match = False
      else:
        added_prev_item = False
        prev_match = False

      prev_art_item = iter_item

  return matches


def get_input(msg: str,
              allowed_resps: list[str] = None) -> str:
  while True:
    ans = input(msg).lower()
    if allowed_resps is None or ans in allowed_resps:
      break
    else:
      print('Invalid response')

  return ans


def format_str(text: str,
               color: int,
               effect1: int = -1,
               effect2: int = -1):
  FMT_PREFIX = '\033['
  fmt_str = f"{FMT_PREFIX}{color}"
  if effect1 >= 0:
    fmt_str += f";{effect1}"
  if effect2 >= 0:
    fmt_str += f";{effect2}"

  return f"{fmt_str}m{text}{FMT_PREFIX}0m"
