from time import sleep

from istari_digital_client import Client, Configuration, Job, Model
from istari_digital_client.models import JobStatusName
from shared.constants import REG_URL, REG_AUTH_TOKEN


job_list = []

def get_client():
  configuration = Configuration(
      registry_url=REG_URL,
      registry_auth_token=REG_AUTH_TOKEN)

  return Client(config = configuration)


def submit_job(model_id: str,
               function: str,
               tool_name: str,
               tool_ver: str = None,
               params_file: str = None) -> Job:
  client = get_client()
  job =  client.add_job(model_id,
                        function = function,
                        tool_name = tool_name,
                        tool_version = tool_ver,
                        parameters_file = params_file)
  job_list.append(job.id)
  return job


def wait_for_job(job) -> Job:
  client = get_client()
  empty_str = ' ' * 64
  while not job.status.name in [JobStatusName.COMPLETED, 
                                JobStatusName.FAILED]:
    sleep(1)
    job = client.get_job(job.id)
    print(empty_str, end="\r")
    job_stat = format_str(job.status.name, 1)
    print(f"Job Status: {job_stat}", end="\r")

  if job.id in job_list:
    job_list.remove(job.id)

  print(empty_str, end="\r")
  return job


def wait_for_all_jobs():
  client = get_client()
  for job_id in job_list:
    job = client.get_job(job_id)
    wait_for_job(job)


def get_model_display_name(model_id: str) -> str:
  client = get_client()
  mod = client.get_model(model_id)
  disp_name = mod.display_name
  if disp_name is None:
    disp_name,_ = os.path.splitext(mod.name)

  return disp_name

def get_latest_revision(model_id: str) -> str:
  client = get_client()
  mod = client.get_model(model_id)
  mod_revs = mod.file.revisions
  ret_rev = None
  for mod_rev in mod_revs:
    if ret_rev == None or ret_rev.created < mod_rev.created:
      ret_rev = mod_rev

  return ret_rev.id
  

def wait_for_new_version(model_id: str) -> Model:
  client = get_client()
  empty_str = ' ' * 64
  mod = client.get_model(model_id)
  revs = mod.file.revisions
  mod_name = revs[0].display_name
  latest_rev = revs[-1]
  rev_count = len(revs)
  while True:
    print(empty_str, end="\r")
    print(f"Polling for model updates: {mod_name}",
          end="\r")
    sleep(5)
    mod = client.get_model(model_id)
    revs = mod.file.revisions
    new_rev_count = len(revs)
    if new_rev_count != rev_count:
      latest_rev = revs[-1]
      break

  print(empty_str, end="\r")
  print(f"Model update detected: {mod_name}")
  return latest_rev


def download_artifact_orig(model_id: str,
                      artifact_name: str,
                      dest_file: str = None):
  client = get_client()
  art = None
  pg_idx = 1
  while True:
    art_list = client.list_model_artifacts(model_id,
                                           page = pg_idx)
    art_items = art_list.items
    if len(art_items) == 0:
      break
    
    for itm in art_items:
      if itm.name == artifact_name:
        art = itm
        break

    if art is not None: break
    pg_idx += 1

  if art is None:
    raise FileNotFoundError(f"Artifact not found: {artifact_name}")
  else:
    if dest_file is None:
      dest_file = artifact_name
    with open(dest_file, 'wb') as fout:
      fout.write(art.read_bytes())


def download_artifact_data(model_id: str,
                           artifact_name: str,
                           art_rev_id: str = None) -> bytes:
  client = get_client()
  mod = client.get_model(model_id)
  des_rev_id = mod.file.revision.id if art_rev_id is None else art_rev_id

  pg_idx = 1
  while True:
    art_list = client.list_model_artifacts(model_id,
                                           page = pg_idx)
    arts = art_list.items
    if len(arts) == 0:
      break
    
    # Find artifact with name matching artifact_name and generated by the latest
    # version of the model
    for art in arts:
      if art.name == artifact_name:
        if art_rev_id is None:
          return art.file.revision.read_bytes()
        else:
          for art_rev in art.file.revisions:
            try:
              if art_rev.id == art_rev_id:
                return art_rev.read_bytes()
            except Exception as excp:
              print(f"Exception: {excp}")

    pg_idx += 1

  raise FileNotFoundError(f"Artifact not found: {artifact_name}")


def download_artifact(model_id: str,
                      artifact_name: str,
                      dest_file: str = None) -> None:
  """
  Downloads the artifact associated with the latest version of the model.

  Throws FileNotFoundError if the artifact is not found.
  """
  art_bytes = download_artifact_data(model_id,
                                     artifact_name)
  if dest_file is None:
    dest_file = artifact_name
  with open(dest_file, 'wb') as fout:
    fout.write(art_bytes)


def download_model_data(model_id: str) -> bytes:
  client = get_client()
  mod = client.get_model(model_id)
  mod_rev = mod.file.revision
  return mod_rev.read_bytes()


def download_model(model_id: str,
                   dest_file: str = None) -> None:
  mod_bytes = download_model_data(model_id)
  if dest_file is None:
    mod = client.get_model(model_id)
    dest_file = mod.display_name
    if dest_file is None:
      dest_file = mod.name

  with open(dest_file, 'wb') as fout:
    fout.write(mod_bytes)


def get_artifact_data(art_rev: object) -> bytes:
  """
  Searches the model cache for the specified artifact revision. If there is a 
  cache hit, returns the cached data. Otherwise, the artifact is downloaded 
  from the Istari platform and cached.
  """
  model_cache_dir = tempfile.gettempdir()
  art_file = os.path.join(model_cache_dir,
                          art_rev.id)
  art_bytes = None
  if False: #os.path.exists(art_file):
    with open(art_file, 'rb') as fin:
      art_bytes = fin.read()
  else:
    art_bytes = art_rev.read_bytes()
    with open(art_file, 'wb') as fout:
      fout.write(art_bytes)
    
  return art_bytes


def format_str(text: str,
               color: int,
               effect1: int = -1,
               effect2: int = -1):
  FMT_PREFIX = '\033['
  fmt_str = f"{FMT_PREFIX}{color}"
  if effect1 >= 0:
    fmt_str += f";{effect1}"
  if effect2 >= 0:
    fmt_str += f";{effect2}"

  return f"{fmt_str}m{text}{FMT_PREFIX}0m"
