import json
import logging

from pydantic import Json

logging.getLogger('openai').setLevel(logging.ERROR)
logging.getLogger('httpx').setLevel(logging.ERROR)


class PdfPageIterator():
  """
    Iterates over a Json array of pdf paragraphs and returns arrays of
    paragraphs corresponding to a page. Useful for the 'text_sections.json'
    artifact generated by the OpenPdf module.
  """
  def __init__(self,
               pdf_json: Json[dict]) -> None:
    self.pdf_json = pdf_json
    self.par_count = len(pdf_json)
    self.par_idx = 0


  def __iter__(self) -> object:
    return self


  def __next__(self) -> Json[dict]:
    if self.par_idx >= self.par_count:
      raise StopIteration

    cur_page_num = 0
    page_json = []
    while True:
      par_json = self.pdf_json[self.par_idx]

      par_page_num = par_json['page_number']
      if not cur_page_num:
        cur_page_num = par_page_num
      elif cur_page_num != par_page_num:
        break

      page_json.append(par_json)

      self.par_idx += 1
      if self.par_idx >= self.par_count:
        break

    return page_json
